# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: Setup Go environment
      uses: actions/setup-go@v5.0.2

    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v6.1.0

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  release:
    needs: build
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            exe: ''
          - os: windows
            exe: '.exe'
          - os: darwin
            exe: ''
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: Setup Go environment
      uses: actions/setup-go@v5.0.2

    - name: Build
      run: |
        GOOS=${{ matrix.os }} GOARCH=amd64 go build -o wsstester-${{ matrix.os }}-amd64${{ matrix.exe }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./wsstester-${{ matrix.os }}-amd64${{ matrix.exe }}
        asset_name: wsstester-${{ matrix.os }}-amd64${{ matrix.exe }}
        asset_content_type: application/octet-stream
